### ISSUE TITLE
WLANPersonalWPA2Connect : Error in WlanNetworkConnect_WPA

### ISSUE THREAD

**Issue by darmat** [xdk2mam/xdk2mam#12]
Dear all,
I tried to flash my XDK with the xdk2mam code for the data marketplace but I get this error message as soon as I boot the device:
INFO | XDK DEVICE 2: WLANPersonalWPA2Connect : Error in WlanNetworkConnect_WPA
INFO | XDK DEVICE 2: Error in WLAN package.
INFO | XDK DEVICE 2: Package ID: 10
INFO | XDK DEVICE 2: Module ID: 2
INFO | XDK DEVICE 2: Severity code: 2
INFO | XDK DEVICE 2: Error code: 71
INFO | XDK DEVICE 2: WLAN_Enable failed with 167911495

Did anyone see this before?

**Comment by demichele** [comment]
Most probably you have something wrong on your WiFi data. Double check SSID and password and be sure not to leave blank spaces after each line in the config file.

**Comment by darmat** [comment]
Unfortunately our SSID has a blank space in the name, I had a thought to use quotes but this did not seem to work. Is there a work around?

**Comment by demichele** [comment]
White spaces on SSID are not a problem. Does the WiFi have a password?

**Comment by darmat** [comment]
Yes, it has an alphanumeric password.

**Comment by darmat** [comment]
I have used XDK for other projects, connecting to the same network, without problems.

**Comment by darmat** [comment]
nothing else to do here.
