### ISSUE TITLE
Error: redeclaration of enumerator 'RETCODE_MQTT_IPCONIG_FAIL'

### ISSUE THREAD

**Issue by dubaleeiro** [xdk2mam/xdk2mam#2]
Hello,
I am getting the following error when buiding the project:
`C:/Users/dubal/Downloads/xdk2mam-master/xdk2mam-master/mqtt/xdk2mam-c/source/xdk2mam-mqtt.h:65:5: error: redeclaration of enumerator 'RETCODE_MQTT_IPCONIG_FAIL'`
I am currently using Workbench v3.4.0 trying to connect to cloudmqtt.com.
Can anyone help please? Thanks.

**Comment by aleelus** [comment]
Hello dubaleeiro,
We have already fixed that error, the problem was that the previous version of the Workbench (v3.3.0) did not have the declaration of the 'RETCODE_MQTT_IPCONFIG_FAIL'.
Now you should be able to build the proyect without any errors.

P.S: sorry for the delayed response.
