### ISSUE TITLE
xdk2mam not starting app in XDK

### ISSUE THREAD

**Issue by mat-l** [xdk2mam/xdk2mam#9]
Dear all,
we just bought a new Bosch XDK and downloaded XDK2MAM. As described, we changed the wifi settings and compiling does not give any errors. After flashing to the XDK we get the following error or info message:

`INFO | XDK DEVICE 1: 
 INFO | XDK DEVICE 1: XMODEM Download Success
 INFO | XDK DEVICE 1:  CRC of application area
 INFO | XDK DEVICE 1:  CRC0000A5B2
 INFO | Application checksum 'a5b2' successfully verified.
 INFO | Transmission successfully completed!
 INFO | Booting application...
 INFO | XDK DEVICE 1: b
 INFO | XDK DEVICE 1:  Jumping to application
 INFO | Port 'COM4' has been disconnected
 INFO | Connecting to XDK device 'XDK Device 1' in port 'COM4'...
 INFO | Connection to port 'COM4' established
 INFO | XDK DEVICE 1: Connect Failed, so example is not started
 INFO | XDK DEVICE 1: System Error:, Severity:2 Error code: 4 Package Id:30 and module ID is :26 
 INFO | XDK DEVICE 1:  Reset the system`

Can you help us identifying the problem, that we can stream the sensor data via MQTT to our server and connect the XDK to IOTAs Tangle?

Best regards

**Comment by demichele** [comment]
Hello @mat-l. Could  you please specify which XDK2MAM MQTT version are you using (MQTT+SDCard or MQTT)? Also, be sure to use the code at the branch that matches your XDK Workbench version. Please, let us know which MQTT pckg you are using. If you are using the SD card triple check your config.cfg file and its values. Keep in mind that with this code you must have the card inserted on the XDK110 micro SD slot **before you flash** the code.

**Comment by mat-l** [comment]
Hello @demichele 
We are using XDK110 without SD card in combination with Workbench 3.6 and also the code related to 3.6 which should be the latest one.

In Workbench I opened this project/code: https://github.com/xdk2mam/xdk2mam/tree/Workbench-3.6/mqtt/xdk2mam-c and adjusted accordingly the WiFi settings and MQTT settings.

Best regards

**Comment by aleelus** [comment]
Hi @mat-l,
That was an old version of the mqtt method, in a few minutes we will upload the updated version of the mqtt method without the sd-scard.
Thanks!

**Comment by demichele** [comment]
Hi @mat-l if you get it to work please let us know so we can close this issue. Thanks for the feedback!

**Comment by mat-l** [comment]
Perfect, great @demichele @aleelus the updated version is working for us. Thanks for the fast feedback and update. :)

**Comment by smileheartravi** [comment]
can I have XDK 110  code for temperature measurement reading over SD card
